_wandb:
    value:
        cli_version: 0.21.1
        e:
            twrr8tw24n1djfp35cykjxpn0lvw3dbe:
                args:
                    - data.train_files=data/numina_cot/train.parquet
                    - data.val_files=data/math500/test.parquet
                    - data.prompt_key=extra_info
                    - data.response_key=extra_info
                    - data.train_batch_size=128
                    - data.max_length=2048
                    - optim.lr=5e-5
                    - data.prompt_dict_keys=[question]
                    - data.response_dict_keys=[answer]
                    - data.micro_batch_size_per_gpu=4
                    - model.partial_pretrain=Qwen/Qwen2.5-Math-1.5B
                    - model.use_liger=True
                    - model.fsdp_config.model_dtype=bf16
                    - trainer.default_local_dir=checkpoints/numina-cot-ndft-qwen-2.5-math-1.5b
                    - trainer.project_name=dft
                    - trainer.experiment_name=numina-cot-ndft-qwen-2.5-math-1.5b-20250820-174343
                    - trainer.logger=[console,wandb]
                    - trainer.default_hdfs_dir=null
                    - trainer.test_freq=10
                    - trainer.save_freq=100
                    - trainer.total_epochs=1
                    - ulysses_sequence_parallel_size=1
                    - use_remove_padding=true
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "137371844608"
                        used: "43051470848"
                email: lixinghan2013@163.com
                executable: /homes/gws/lxh22/miniconda3/envs/DFT/bin/python3.10
                git:
                    commit: 78d0ca2f31eb7771fa67345dea377bce3a301d86
                    remote: https://github.com/xh092113/DFT.git
                gpu: NVIDIA A40
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-3f1d0711-9b0a-f0d3-7bfd-d86c03be6e20
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-6dae52a7-515c-e39f-9be0-ed10d7224d11
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-51dc802a-0e98-7114-e16a-05e1d189b564
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-50ceae54-e443-bbd7-1cf5-017952a91545
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-9e63af74-5304-12ae-dc5f-7fb92bb0f27e
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-9da0de31-e059-4cb8-a2eb-107570a77dca
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-4ba1d24a-b789-4ed5-3d83-552fef8d3f2c
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-1a95ee14-4732-0786-edff-1ec1d55b6cc6
                host: du-exxact-0.cs.washington.edu
                memory:
                    total: "1081981837312"
                os: Linux-5.14.0-570.28.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: -m verl.trainer.fsdp_ndft_trainer
                python: CPython 3.10.18
                root: /homes/gws/lxh22/rl-sft/DFT/verl
                startedAt: "2025-08-21T00:44:16.463647Z"
                writerId: twrr8tw24n1djfp35cykjxpn0lvw3dbe
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "3":
                - 13
                - 61
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.51.1
            "12": 0.21.1
            "13": linux-x86_64
