_wandb:
    value:
        cli_version: 0.21.1
        e:
            b8kinjd2zqhoqrbarat1nnq1dr0lauc1:
                args:
                    - data.train_files=data/pi1/pi1_r128_pm_responses_16000.parquet
                    - data.val_files=data/pi1/pi1_r128_pm_responses_16000_valid.parquet
                    - data.max_length=1920
                    - data.prompt_key=prompt
                    - data.response_key=response
                    - data.train_batch_size=256
                    - data.micro_batch_size_per_gpu=4
                    - model.partial_pretrain=/homes/gws/lxh22/models/Qwen2.5-Math-7B
                    - trainer.default_local_dir=/local1/lxh/save/offline_grpo/7b_pi1_ofrl
                    - trainer.project_name=dft
                    - trainer.experiment_name=7b_pi1_ofrl_0904-1037
                    - trainer.total_epochs=1
                    - trainer.test_freq=10
                    - trainer.save_freq=10
                    - trainer.total_training_steps=40
                    - trainer.logger=[console,wandb]
                    - trainer.default_hdfs_dir=null
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "274608492544"
                        used: "28786176000"
                email: lixinghan2013@163.com
                executable: /homes/gws/lxh22/miniconda3/envs/DFT/bin/python3.10
                git:
                    commit: 1b94c1c106a51b8901fcdfb31cb862c1fcab6b64
                    remote: git@github.com:xh092113/rl-sft.git
                gpu: NVIDIA RTX A6000
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-c9bba159-5476-3617-7251-130c2b28c0af
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-2a207ebe-3917-0535-32af-fb9963b34e7a
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-28ddb46e-709a-a007-62ea-c7a0b97ed33d
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-5af35f33-8a6b-7b5b-17dd-c4024f600e47
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-1a9efb90-4ca1-08c4-82c9-2c1fe3539b3f
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-3ff18936-8430-23c0-ded1-7bcea6f2963e
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-4c4af347-6692-5350-713c-8bfba0d4eed4
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-54b7145f-87d4-16a1-08b9-a9a67cddc759
                host: fazel-du-exxact-0.cs.washington.edu
                memory:
                    total: "1081979883520"
                os: Linux-5.14.0-570.28.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: -m verl.trainer.fsdp_ofrl_trainer
                python: CPython 3.10.18
                root: /homes/gws/lxh22/rl-sft/DFT/verl
                startedAt: "2025-09-04T17:38:14.867868Z"
                writerId: b8kinjd2zqhoqrbarat1nnq1dr0lauc1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "3":
                - 13
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.51.1
            "12": 0.21.1
            "13": linux-x86_64
